

for i in $(seq 0 9);
do
    poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_celeba_inverse/../main.py --run_name Tunable_Inverse_DP_015 --project_name Celeba_continual_Results --node_shuffle_seed $i --alpha_target_lambda=1.6770070166194004 --batch_size=57 --clipping=10.771456926805136 --epochs=2 --lr=0.07870036497709101 --momentum=0.42969499995252425 --optimizer=sgd --weight_decay_lambda=0.622687647970531 --dataset celeba --num_rounds 40 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.2 --sampled_clients_test 1.0 --train_csv df_not_attractive --train_csv_shift df_attractive --debug False --base_path ../../../../data/ --dataset_path ../../../../data/celeba/ --seed 41 --wandb True  --training_nodes 0.67 --test_nodes 0.335 --partition_type representative --group_to_reduce 1 1 --group_to_increment 0 1 --number_of_samples_per_node 800 --ratio_unfair_nodes 0.5 --ratio_unfairness 0 0 --number_of_samples_per_node_shift 420 --ratio_unfair_nodes_shift 0.5 --ratio_unfairness_shift 0 0 --splitted_data_dir federated_2 --shift True --switch_dataset 21 --regularization_mode tunable --regularization True --target 0.15 --global_computation True --epsilon 3.5 --epsilon_statistics 0.5 --epsilon_lambda 1
done

# for i in $(seq 1 4);
# do
#     poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_celeba_inverse/../main.py --run_name Fixed_Inverse_DP_015 --project_name Celeba_continual_Results --node_shuffle_seed $i  --batch_size=136 --clipping=8.065495684607544 --epochs=5 --lr=0.08261543647852482 --optimizer=sgd --regularization_lambda=0.5348314908316406 --dataset celeba --num_rounds 40 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.2 --sampled_clients_test 1 --train_csv df_not_attractive --train_csv_shift df_attractive --debug False --base_path ../../../../data/ --dataset_path ../../../../data/celeba/ --seed 41 --wandb True  --training_nodes 0.67 --test_nodes 0.335 --partition_type representative --group_to_reduce 1 1 --group_to_increment 0 1 --number_of_samples_per_node 800 --ratio_unfair_nodes 0.5 --ratio_unfairness 0 0 --number_of_samples_per_node_shift 420 --ratio_unfair_nodes_shift 0.5 --ratio_unfairness_shift 0 0 --splitted_data_dir federated --shift True --switch_dataset 21 --regularization_mode fixed --regularization True --target 0.15 --epsilon 4.5 --epsilon_statistics 0.5
# done

# for i in $(seq 7 10);
# do
#     poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_celeba_inverse/../main.py --run_name Tunable_Inverse_DP --project_name Celeba_continual_Results --node_shuffle_seed $i --alpha_target_lambda=2.287309102788351 --batch_size=483 --clipping=6.055274597685687 --epochs=4 --lr=0.012072059753931963 --momentum=0.4645771646512628 --optimizer=adam --weight_decay_lambda=0.2228076040736083 --dataset celeba --num_rounds 40 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.2 --sampled_clients_test 1--train_csv df_not_attractive --train_csv_shift df_attractive --debug False --base_path ../../../../data/ --dataset_path ../../../../data/celeba/ --seed 41 --wandb True --training_nodes 0.67 --test_nodes 0.335 --partition_type representative --group_to_reduce 1 1 --group_to_increment 0 1 --number_of_samples_per_node 800 --ratio_unfair_nodes 0.5 --ratio_unfairness 0 0 --number_of_samples_per_node_shift 420 --ratio_unfair_nodes_shift 0.5 --ratio_unfairness_shift 0 0 --splitted_data_dir federated --shift True --switch_dataset 21 --regularization_mode tunable --regularization True --target 0.05 --global_computation True --epsilon 3.5 --epsilon_statistics 0.5 --epsilon_lambda 1
# done

# for i in $(seq 12 15);
# do
#     poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_celeba_inverse/../main.py --run_name Tunable_Inverse_DP --project_name Celeba_continual_Results --node_shuffle_seed $i --alpha_target_lambda=2.642340869781754 --batch_size=402 --clipping=4.370211261972305 --epochs=2 --lr=0.05062424904194719 --momentum=0.8812856217631667 --optimizer=sgd --weight_decay_lambda=0.2968054905469948 --dataset celeba --num_rounds 40 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.2 --sampled_clients_test 1 --train_csv df_not_attractive --train_csv_shift df_attractive --debug False --base_path ../../../../data/ --dataset_path ../../../../data/celeba/ --seed 41 --wandb True --training_nodes 0.67 --test_nodes 0.335 --partition_type representative --group_to_reduce 1 1 --group_to_increment 0 1 --number_of_samples_per_node 800 --ratio_unfair_nodes 0.5 --ratio_unfairness 0 0 --number_of_samples_per_node_shift 420 --ratio_unfair_nodes_shift 0.5 --ratio_unfairness_shift 0 0 --splitted_data_dir federated_2 --shift True --switch_dataset 21 --regularization_mode tunable --regularization True --target 0.05 --global_computation True --epsilon 3.5 --epsilon_statistics 0.5 --epsilon_lambda 1
# done

# # Fixed 
# for i in $(seq 33 36);
# do
#     poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_celeba_inverse/../main.py --run_name Fixed_Inverse_DP --project_name Celeba_continual_Results --node_shuffle_seed $i --batch_size=267 --clipping=2.5858835236166833 --epochs=5 --lr=0.07149915499426847 --optimizer=sgd --regularization_lambda=0.6414301646372773 --dataset celeba --num_rounds 40 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.2 --sampled_clients_test 1 --train_csv df_not_attractive --train_csv_shift df_attractive --debug False --base_path ../../../../data/ --dataset_path ../../../../data/celeba/ --seed 41 --wandb True --training_nodes 0.67 --test_nodes 0.335 --partition_type representative --group_to_reduce 1 1 --group_to_increment 0 1 --number_of_samples_per_node 800 --ratio_unfair_nodes 0.5 --ratio_unfairness 0 0 --number_of_samples_per_node_shift 420 --ratio_unfair_nodes_shift 0.5 --ratio_unfairness_shift 0 0 --splitted_data_dir federated --shift True --switch_dataset 21 --regularization_mode fixed --regularization True --target 0.05 --epsilon 4.5 --epsilon_statistics 0.5
# done

# for i in $(seq 55 58);
# do
#     poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_celeba_inverse/../main.py --run_name Fixed_Inverse_DP --project_name Celeba_continual_Results --node_shuffle_seed $i --batch_size=169 --clipping=16.36448715899219 --epochs=2 --lr=0.025613348800083344 --optimizer=adam --regularization_lambda=0.8303676690214443 --dataset celeba --num_rounds 40 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.2 --sampled_clients_test 1 --train_csv df_not_attractive --train_csv_shift df_attractive --debug False --base_path ../../../../data/ --dataset_path ../../../../data/celeba/ --seed 41 --wandb True --training_nodes 0.67 --test_nodes 0.335 --partition_type representative --group_to_reduce 1 1 --group_to_increment 0 1 --number_of_samples_per_node 800 --ratio_unfair_nodes 0.5 --ratio_unfairness 0 0 --number_of_samples_per_node_shift 420 --ratio_unfair_nodes_shift 0.5 --ratio_unfairness_shift 0 0 --splitted_data_dir federated_2 --shift True --switch_dataset 21 --regularization_mode fixed --regularization True --target 0.05 --epsilon 4.5 --epsilon_statistics 0.5
# done

# for i in $(seq 77 80);
# do
#     poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_celeba_inverse/../main.py --run_name Fixed_Inverse_DP --project_name Celeba_continual_Results --node_shuffle_seed $i --batch_size=278 --clipping=14.22805195832344 --epochs=3 --lr=0.08440992012301242 --optimizer=sgd --regularization_lambda=0.8770341366096892 --dataset celeba --num_rounds 40 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.2 --sampled_clients_test 1 --train_csv df_not_attractive --train_csv_shift df_attractive --debug False --base_path ../../../../data/ --dataset_path ../../../../data/celeba/ --seed 41 --wandb True --training_nodes 0.67 --test_nodes 0.335 --partition_type representative --group_to_reduce 1 1 --group_to_increment 0 1 --number_of_samples_per_node 800 --ratio_unfair_nodes 0.5 --ratio_unfairness 0 0 --number_of_samples_per_node_shift 420 --ratio_unfair_nodes_shift 0.5 --ratio_unfairness_shift 0 0 --splitted_data_dir federated --shift True --switch_dataset 21 --regularization_mode fixed --regularization True --target 0.05 --epsilon 4.5 --epsilon_statistics 0.5
# done