[project]
name = "puffle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lucacorbucci", email = "corbuccilu@gmail.com" }
]
requires-python = ">=3.11, <3.13"
dependencies = [
    "aif360>=0.6.1",
    "complexipy>=5.1.0",
    "flwr-datasets>=0.5.0",
    "flwr[simulation]>=1.22.0",
    "folktables>=0.0.12",
    "google-api-python-client>=2.169.0",
    "ipykernel>=6.29.5",
    "numpy>=2.2.0",
    "nvitop>=1.5.2",
    "opacus>=1.5.4",
    "pandas>=2.2.3",
    "peft>=0.17.1",
    "pytest>=8.3.5",
    "ruff>=0.11.10",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
    "tqdm>=4.67.1",
    "ty>=0.0.1a5",
    "wandb>=0.19.11",
]

[project.scripts]
puffle = "puffle:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest-cov>=7.0.0",
    "ty>=0.0.1a5",
]

[tool.ruff.lint]
select = [
    "ALL", # include all the rules, including new ones
]
ignore = [
    #### modules
    "ANN", # flake8-annotations
    "COM", # flake8-commas
    "C90", # mccabe complexity
    "DJ",  # django
    "EXE", # flake8-executable
    "T10", # debugger
    "TID", # flake8-tidy-imports
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
    "W191", # indentation contains tabs
    #### specific rules
    "D100",   # ignore missing docs
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D205",
    "D212",
    "D400",
    "D401",
    "D415",
    "E402",   # false positives for local imports
    "E501",   # line too long
    "TRY003", # external messages in exceptions are too verbose
    "TD002",
    "TD003",
    "FIX002", # too verbose descriptions of todos
    "N812",   # lowercase functional as F is standard
    "PLW2901", # loop variable overwritten is common in this codebase
]

[tool.ruff.lint.pylint]
max-args = 12

[tool.ruff.lint.per-file-ignores]
"src/puffle/tests/*" = ["S101", "PLR2004", "D101", "D102", "D103", "SLF001", "PT011"]
"src/puffle/examples/*" = ["D103", "T201", "F401", "FBT001", "FBT002", "PTH118", "PLR2004", "PLW2901", "NPY002", "PLC0415", "F841", "PGH003"]
"src/puffle/Regularization/error_rate_regularization_loss.py" = ["PLR0912", "PLR0915", "ARG002", "ARG004", "BLE001"]
"src/puffle/Regularization/disparity_loss.py" = ["PLR0912", "ARG002"]
"src/puffle/PUFFLEModel/puffle_model.py" = ["T201", "PLR0913"]
