program: main.py
method: random
metric:
  name: Custom_metric
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 3
parameters:
  num_rounds:
    values: [20, 30, 40, 50, 60, 70, 80, 90, 100]
  epochs:
    min: 1
    max: 5
  batch_size:
    min: 128
    max: 512
  lr:
    min: 0.0001
    max: 0.1
  clipping:
    min: 5
    max: 10
  weight_decay_lambda:
    min: 0.0001
    max: 0.1
  optimizer:
    values: ["adam", "sgd", "adamw"]
  alpha_target_lambda:
    min: 0.1
    max: 4.0

command:
  - ${env}
  - poetry 
  - run 
  - python
  - ${program}
  - ${args}
  - --dataset
  - celeba
  - --num_client_cpus
  - 1
  - --num_client_gpus
  - 0.5 
  - --pool_size
  - 100
  - --sampled_clients 
  - 0.1
  - --train_csv
  - unfair_train
  - --test_csv 
  - unfair_test
  - --debug
  - True 
  - --base_path
  - ../data 
  - --DPL 
  - True 
  - --private 
  - True 
  - --delta 
  - 1e-4 
  - --partition_type 
  - non_iid 
  - --alpha 
  - 5 
  - --seed 
  - 41 
  - --wandb 
  - True 
  - --target 
  - 0.1
  - --sweep
  - True
  - --validation_ratio
  - 0.2
  - --epsilon
  - 10