# # tunable_005_DP_2
# for i in $(seq 1 4);
# do
#     CUDA_VISIBLE_DEVICES=4 poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_income_new_test/../main.py --run_name Tunable_new_test --node_shuffle_seed $i --project_name Continual_Income_Two_switch --alpha_target_lambda=1.1466501856958682 --batch_size=312 --epochs=2 --lr=0.03415363007368877 --momentum=0.2336601708924506 --optimizer=adam --weight_decay_lambda=0.3094504806561856 --dataset continual_income --num_rounds 20 --num_client_cpus 1 --num_client_gpus 0.05 --pool_size 150 --sampled_clients 0.18 --sampled_clients_test 1 --debug False --base_path ../../../../data/continual_income/ --dataset_path ../../../../data/continual_income/ --seed 42 --wandb True --training_nodes 0.67 --test_nodes 0.335 --tabular_data True --metric disparity --splitted_data_dir federated_3 --switch_dataset 11 --ratio_unfair_nodes 0.5 --regularization_mode tunable --regularization True --target 0.05
# done


# CUDA_VISIBLE_DEVICES=4 poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_income_new_test/../main.py --run_name All --node_shuffle_seed 1 --project_name Continual_Income_Two_switch --alpha_target_lambda=3.82 --batch_size=312 --epochs=2 --lr=0.03415363007368877 --momentum=0.53 --optimizer=adam --weight_decay_lambda=0.55 --dataset continual_income --num_rounds 20 --num_client_cpus 1 --num_client_gpus 0.05 --pool_size 150 --sampled_clients 0.18 --sampled_clients_test 1 --debug False --base_path ../../../../data/continual_income/ --dataset_path ../../../../data/continual_income/ --seed 42 --wandb True --training_nodes 0.67 --test_nodes 0.335 --tabular_data True --metric disparity --splitted_data_dir federated_3 --switch_dataset 11 --ratio_unfair_nodes 0.5 --regularization_mode tunable --regularization True --target 0.05


CUDA_VISIBLE_DEVICES=4 poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_income_new_test/../main.py --run_name Alpha --node_shuffle_seed 1 --project_name Continual_Income_Two_switch --alpha_target_lambda=3.82 --batch_size=312 --epochs=2 --lr=0.03415363007368877 --momentum=0.2336601708924506 --optimizer=adam --weight_decay_lambda=0.3094504806561856 --dataset continual_income --num_rounds 20 --num_client_cpus 1 --num_client_gpus 0.05 --pool_size 150 --sampled_clients 0.18 --sampled_clients_test 1 --debug False --base_path ../../../../data/continual_income/ --dataset_path ../../../../data/continual_income/ --seed 42 --wandb True --training_nodes 0.67 --test_nodes 0.335 --tabular_data True --metric disparity --splitted_data_dir federated_3 --switch_dataset 11 --ratio_unfair_nodes 0.5 --regularization_mode tunable --regularization True --target 0.05


CUDA_VISIBLE_DEVICES=4 poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_income_new_test/../main.py --run_name Momentum --node_shuffle_seed 1 --project_name Continual_Income_Two_switch --alpha_target_lambda=1.1466501856958682 --batch_size=312 --epochs=2 --lr=0.03415363007368877 --momentum=0.53 --optimizer=adam --weight_decay_lambda=0.3094504806561856 --dataset continual_income --num_rounds 20 --num_client_cpus 1 --num_client_gpus 0.05 --pool_size 150 --sampled_clients 0.18 --sampled_clients_test 1 --debug False --base_path ../../../../data/continual_income/ --dataset_path ../../../../data/continual_income/ --seed 42 --wandb True --training_nodes 0.67 --test_nodes 0.335 --tabular_data True --metric disparity --splitted_data_dir federated_3 --switch_dataset 11 --ratio_unfair_nodes 0.5 --regularization_mode tunable --regularization True --target 0.05


CUDA_VISIBLE_DEVICES=4 poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_income_new_test/../main.py --run_name Decay --node_shuffle_seed 1 --project_name Continual_Income_Two_switch --alpha_target_lambda=1.1466501856958682 --batch_size=312 --epochs=2 --lr=0.03415363007368877 --momentum=0.2336601708924506 --optimizer=adam --weight_decay_lambda=0.55 --dataset continual_income --num_rounds 20 --num_client_cpus 1 --num_client_gpus 0.05 --pool_size 150 --sampled_clients 0.18 --sampled_clients_test 1 --debug False --base_path ../../../../data/continual_income/ --dataset_path ../../../../data/continual_income/ --seed 42 --wandb True --training_nodes 0.67 --test_nodes 0.335 --tabular_data True --metric disparity --splitted_data_dir federated_3 --switch_dataset 11 --ratio_unfair_nodes 0.5 --regularization_mode tunable --regularization True --target 0.05
