# for i in $(seq 4 7);
# do
#     poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_celeba/../main.py --run_name Baseline_NO_DP --project_name Celeba_continual_Results --node_shuffle_seed $i --batch_size=259 --epochs=3 --lr=0.003529605553902901 --optimizer=adam --dataset celeba --num_rounds 40 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.20 --sampled_clients_test 1.0 --train_csv df_attractive --train_csv_shift df_not_attractive --debug False --base_path ../../../../data/ --dataset_path ../../../../data/celeba/ --seed 41 --wandb True  --training_nodes 0.67 --test_nodes 0.335 --partition_type representative --group_to_reduce 1 1 --group_to_increment 0 1 --number_of_samples_per_node 420 --ratio_unfair_nodes 0.5 --ratio_unfairness 0 0 --number_of_samples_per_node_shift 800 --ratio_unfair_nodes_shift 0.5 --ratio_unfairness_shift 0 0 --splitted_data_dir federated --shift True --switch_dataset 21
# done 

# for i in $(seq 4 7);
# do
#     poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_celeba/../main.py --run_name Fixed_Target_005_NO_DP --project_name Celeba_continual_Results --node_shuffle_seed $i --batch_size=216 --epochs=4 --lr=0.00954907580428935 --optimizer=adam --regularization_lambda=0.2060959773268679 --dataset celeba --num_rounds 40 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.20 --sampled_clients_test 1.0 --train_csv df_attractive --train_csv_shift df_not_attractive --debug False --base_path ../../../../data/ --dataset_path ../../../../data/celeba/ --seed 41 --wandb True  --training_nodes 0.67 --test_nodes 0.335 --partition_type representative --group_to_reduce 1 1 --group_to_increment 0 1 --number_of_samples_per_node 420 --ratio_unfair_nodes 0.5 --ratio_unfairness 0 0 --number_of_samples_per_node_shift 800 --ratio_unfair_nodes_shift 0.5 --ratio_unfairness_shift 0 0 --splitted_data_dir federated_3 --shift True --switch_dataset 21 --regularization_mode fixed --regularization True --target 0.05
# done 

for i in $(seq 4 7);
do
    poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_celeba/../main.py --run_name Tunable_Target_005_NO_DP --project_name Celeba_continual_Results --node_shuffle_seed $i --alpha_target_lambda=3.937034223736805 --batch_size=40 --epochs=2 --lr=0.04315759563925755 --momentum=0.23288355086609233 --optimizer=sgd --weight_decay_lambda=0.5017895894486847 --dataset celeba --num_rounds 40 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.20 --sampled_clients_test 1.0 --train_csv df_attractive --train_csv_shift df_not_attractive --debug False --base_path ../../../../data/ --dataset_path ../../../../data/celeba/ --seed 41 --wandb True  --training_nodes 0.67 --test_nodes 0.335 --partition_type representative --group_to_reduce 1 1 --group_to_increment 0 1 --number_of_samples_per_node 420 --ratio_unfair_nodes 0.5 --ratio_unfairness 0 0 --number_of_samples_per_node_shift 800 --ratio_unfair_nodes_shift 0.5 --ratio_unfairness_shift 0 0 --splitted_data_dir federated_2 --shift True --switch_dataset 21 --regularization_mode tunable --regularization True --target 0.05 --global_computation True
done 

