for i in $(seq 10 15);
do
    poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_celeba_new_test/../main.py --run_name Baseline_new_test_3 --project_name Celeba_continual_Results --node_shuffle_seed $i --batch_size=443 --clipping=3.759905436981698 --epochs=4 --lr=0.0508278212453724 --optimizer=adam --dataset celeba --num_rounds 40 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.2 --sampled_clients_test 1 --train_csv df_attractive_new_test --train_csv_shift df_not_attractive_new_test --debug False --base_path ../../../../data/ --dataset_path ../../../../data/celeba/ --seed 41 --wandb True --training_nodes 0.67 --test_nodes 0.335 --partition_type representative --group_to_reduce 1 1 --group_to_increment 0 1 --number_of_samples_per_node 530 --ratio_unfair_nodes 0.5 --ratio_unfairness 0 0 --number_of_samples_per_node_shift 750 --ratio_unfair_nodes_shift 0.5 --ratio_unfairness_shift 0 0 --splitted_data_dir federated_3 --shift True --switch_dataset 21 --epsilon 5
done

for i in $(seq 10 15);
do
    poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_celeba_new_test/../main.py --run_name Fixed_new_test_3 --project_name Celeba_continual_Results --node_shuffle_seed $i --batch_size=304 --clipping=4.76191532908549 --epochs=3 --lr=0.033101951024434584 --optimizer=adam --regularization_lambda=0.31291585432065017 --dataset celeba --num_rounds 40 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.2 --sampled_clients_test 1 --train_csv df_attractive_new_test --train_csv_shift df_not_attractive_new_test --debug False --base_path ../../../../data/ --dataset_path ../../../../data/celeba/ --seed 41 --wandb True --training_nodes 0.67 --test_nodes 0.335 --partition_type representative --group_to_reduce 1 1 --group_to_increment 0 1 --number_of_samples_per_node 530 --ratio_unfair_nodes 0.5 --ratio_unfairness 0 0 --number_of_samples_per_node_shift 750 --ratio_unfair_nodes_shift 0.5 --ratio_unfairness_shift 0 0 --splitted_data_dir federated_3 --shift True --switch_dataset 21 --regularization_mode fixed --regularization True --target 0.05 --epsilon 4.5 --epsilon_statistics 0.5
done

for i in $(seq 10 15);
do
    poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/continual_celeba_new_test/../main.py --run_name Tunable_new_test_3 --project_name Celeba_continual_Results --node_shuffle_seed $i --alpha_target_lambda=2.6058495041731966 --batch_size=456 --clipping=4.128668621760824 --epochs=4 --lr=0.03294569847894035 --momentum=0.6128101879937637 --optimizer=adam --weight_decay_lambda=0.4509151671536017 --dataset celeba --num_rounds 40 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.2 --sampled_clients_test 1 --train_csv df_attractive_new_test --train_csv_shift df_not_attractive_new_test --debug False --base_path ../../../../data/ --dataset_path ../../../../data/celeba/ --seed 41 --wandb True --training_nodes 0.67 --test_nodes 0.335 --partition_type representative --group_to_reduce 1 1 --group_to_increment 0 1 --number_of_samples_per_node 530 --ratio_unfair_nodes 0.5 --ratio_unfairness 0 0 --number_of_samples_per_node_shift 750 --ratio_unfair_nodes_shift 0.5 --ratio_unfairness_shift 0 0 --splitted_data_dir federated_3 --shift True --switch_dataset 21 --regularization_mode tunable --regularization True --target 0.05 --global_computation True --epsilon 3.5 --epsilon_statistics 0.5 --epsilon_lambda 1
done