# # Baseline Dutch one group
# poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/valerio/../main.py --batch_size=135 --epochs=5 --lr=0.08494082308990873 --node_shuffle_seed=266223510 --optimizer=adam --dataset dutch --num_rounds 20 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.20 --sampled_clients_test 0.5 --debug True --base_path ../../../../data/dutch/ --seed 41 --wandb True --sweep True --training_nodes 0.67 --test_nodes 0.335 --tabular_data True --dataset_path ../../../../data/dutch/ --group_to_reduce 0 1 --group_to_increment 1 1 --number_of_samples_per_node 343 --ratio_unfair_nodes 0.5 --ratio_unfairness 0.6 0.8 --approach representative --one_group_nodes True --splitted_data_dir federated_3 --metric disparity  --project_name valerio --run_name Dutch_one_group_baseline --store_model True --file_name baseline_dutch_one_group

# # Dutch one group - Epsilon 1
# poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/valerio/../main.py --batch_size=35 --clipping=1.205945116258495 --epochs=4 --lr=0.07292582361192784 --node_shuffle_seed=562256043 --optimizer=sgd --dataset dutch --num_rounds 20 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.20 --sampled_clients_test 1 --debug True --base_path ../../../../data/dutch/ --seed 41 --wandb True --sweep True --training_nodes 0.67 --test_nodes 0.335 --tabular_data True --dataset_path ../../../../data/dutch/ --group_to_reduce 0 1 --group_to_increment 1 1 --number_of_samples_per_node 343 --ratio_unfair_nodes 0.5 --ratio_unfairness 0.6 0.8 --approach representative --one_group_nodes True --splitted_data_dir federated_3 --metric disparity --epsilon 1 --project_name valerio --run_name Dutch_one_group_epsilon_1  --store_model True --file_name dutch_one_group_epsilon_1

# # Dutch one group - Epsilon 0.5
# poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/valerio/../main.py --batch_size=73 --clipping=2.2605543251689415 --epochs=4 --lr=0.09449493582831547 --node_shuffle_seed=389410664 --optimizer=sgd --dataset dutch --num_rounds 20 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.20 --sampled_clients_test 0.5 --debug True --base_path ../../../../data/dutch/ --seed 41 --wandb True --sweep True --training_nodes 0.67 --test_nodes 0.335 --tabular_data True --dataset_path ../../../../data/dutch/ --group_to_reduce 0 1 --group_to_increment 1 1 --number_of_samples_per_node 343 --ratio_unfair_nodes 0.5 --ratio_unfairness 0.6 0.8 --approach representative --one_group_nodes True --splitted_data_dir federated_3 --metric disparity --epsilon 0.5 --project_name valerio --run_name Dutch_one_group_epsilon_05 --store_model True --file_name dutch_one_group_epsilon_05



# # Income Baseline
# poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/valerio/../main.py --batch_size=815 --epochs=1 --lr=0.09384385849053498 --node_shuffle_seed=24209495 --optimizer=adam --dataset income --num_rounds 10 --num_client_cpus 1 --num_client_gpus 0.05 --pool_size 51 --sampled_clients 0.34 --sampled_clients_test 0.5 --debug False --base_path ../../../../data/income/ --dataset_path ../../../../data/income/ --seed 41 --wandb True --sweep True --training_nodes 0.81 --test_nodes 0.2 --tabular_data True --update_lambda False --metric disparity --splitted_data_dir federated_2 --project_name valerio --run_name Income_baseline --store_model True --file_name baseline_income

# # Income Epsilon 1.0
# poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/valerio/../main.py --batch_size=946 --clipping=2.5069826250340252 --epochs=4 --lr=0.08303400881974693 --node_shuffle_seed=725426356 --optimizer=adam --dataset income --num_rounds 10 --num_client_cpus 1 --num_client_gpus 0.05 --pool_size 51 --sampled_clients 0.34 --sampled_clients_test 0.5 --debug False --base_path ../../../../data/income/ --dataset_path ../../../../data/income/ --seed 41 --wandb True --sweep True --training_nodes 0.81 --test_nodes 0.2 --tabular_data True --metric disparity --epsilon 1 --splitted_data_dir federated --project_name valerio --run_name Income_epsilon_1 --store_model True --file_name epsilon_1_income

# # Income Epsilon 2.0
# poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/valerio/../main.py --batch_size=727 --clipping=2.676005784558546 --epochs=2 --lr=0.01623593884343126 --node_shuffle_seed=723765211 --optimizer=adam --dataset income --num_rounds 10 --num_client_cpus 1 --num_client_gpus 0.05 --pool_size 51 --sampled_clients 0.34 --sampled_clients_test 0.5 --debug False --base_path ../../../../data/income/ --dataset_path ../../../../data/income/ --seed 41 --wandb True --sweep True --training_nodes 0.81 --test_nodes 0.2 --tabular_data True --metric disparity --epsilon 2 --splitted_data_dir federated --project_name valerio --run_name Income_epsilon_2 --store_model True --file_name epsilon_2_income

# # Income Baseline - One Group
# poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/valerio/../main.py --batch_size=1481 --epochs=3 --lr=0.0772935420215819 --node_shuffle_seed=937275932 --optimizer=adam --dataset income --num_rounds 10 --num_client_cpus 1 --num_client_gpus 0.05 --pool_size 51 --sampled_clients 0.34 --sampled_clients_test 0.5 --debug False --base_path ../../../../data/income/ --dataset_path ../../../../data/income/ --seed 41 --wandb True --sweep True --training_nodes 0.81 --test_nodes 0.2 --tabular_data True --one_group_nodes True --update_lambda False --metric disparity --splitted_data_dir federated_2 --project_name valerio --run_name Income_one_group_baseline --store_model True --file_name baseline_income_one_group

# # Income Epsilon 1.0 - One Group
# poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/valerio/../main.py --batch_size=1076 --clipping=1.2627898125338826 --epochs=2 --lr=0.08192467336050896 --node_shuffle_seed=740802234 --optimizer=adam --dataset income --num_rounds 10 --num_client_cpus 1 --num_client_gpus 0.05 --pool_size 51 --sampled_clients 0.34 --sampled_clients_test 0.5 --debug False --base_path ../../../../data/income/ --dataset_path ../../../../data/income/ --seed 41 --wandb True --sweep True --training_nodes 0.81 --test_nodes 0.2 --tabular_data True --one_group_nodes True --metric disparity --epsilon 1 --splitted_data_dir federated  --project_name valerio --run_name Income_one_group_epsilon_1 --store_model True --file_name epsilon_1_income_one_group

# # Income Epsilon 2.0 - One Group
# poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/valerio/../main.py --batch_size=1248 --clipping=18.082820530385188 --epochs=5 --lr=0.0385737629316618 --node_shuffle_seed=14847868 --optimizer=adam --dataset income --num_rounds 10 --num_client_cpus 1 --num_client_gpus 0.05 --pool_size 51 --sampled_clients 0.34 --sampled_clients_test 0.5 --debug False --base_path ../../../../data/income/ --dataset_path ../../../../data/income/ --seed 41 --wandb True --sweep True --training_nodes 0.81 --test_nodes 0.2 --tabular_data True --one_group_nodes True --metric disparity --epsilon 2 --splitted_data_dir federated --project_name valerio --run_name Income_one_group_epsilon_2 --store_model True --file_name epsilon_2_income_one_group

# Baseline two layers
# poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/valerio/../main.py --batch_size=1525 --epochs=5 --lr=0.01875477834948012 --node_shuffle_seed=106099386 --optimizer=adam --dataset income_valerio --num_rounds 10 --num_client_cpus 1 --num_client_gpus 0.05 --pool_size 51 --sampled_clients 0.20 --sampled_clients_test 0.5 --debug False --base_path ../../../../data/income/ --dataset_path ../../../../data/income/ --seed 41 --wandb True --training_nodes 0.81 --test_nodes 0.2 --tabular_data True --update_lambda False --metric disparity --splitted_data_dir federated_2 --project_name valerio --run_name Income_Baseline_two_layers --store_model True --file_name Income_Baseline_two_layers

# Two layers Dutch 
poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/valerio/../main.py --batch_size=67 --epochs=3 --lr=0.0964119734048005 --node_shuffle_seed=992970682 --optimizer=sgd --dataset dutch_valerio --num_rounds 20 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 150 --sampled_clients 0.20 --sampled_clients_test 1.0 --debug True --base_path ../../../../data/dutch/ --seed 41 --wandb True  --training_nodes 0.67 --test_nodes 0.335 --tabular_data True --dataset_path ../../../../data/dutch/ --group_to_reduce 0 1 --group_to_increment 1 1 --number_of_samples_per_node 343 --ratio_unfair_nodes 0.5 --ratio_unfairness 0.6 0.8 --approach representative --splitted_data_dir federated --metric disparity --project_name valerio --run_name Dutch_Baseline_two_layers --store_model True --file_name Dutch_Baseline_two_layers

# poetry run python /home/lcorbucci/Unfairness-Regularization/examples/FederatedLearningDebias/valerio/../main.py --batch_size=50 --epochs=5 --lr=0.0390354994362202 --node_shuffle_seed=850277193 --optimizer=adam --dataset dutch_valerio --num_rounds 20 --num_client_cpus 1 --num_client_gpus 0.1 --pool_size 70 --sampled_clients 0.20 --sampled_clients_test 1 --debug True --base_path ../../../../data/dutch/ --seed 41 --wandb True --training_nodes 0.7 --test_nodes 0.29 --tabular_data True --dataset_path ../../../../data/dutch/ --group_to_reduce 0 1 --group_to_increment 1 1 --number_of_samples_per_node 700 --ratio_unfair_nodes 0.5 --ratio_unfairness 0.6 0.8 --approach representative --splitted_data_dir federated --metric disparity --project_name valerio --run_name Dutch_Baseline_two_layers_70_nodi --store_model True --file_name Dutch_Baseline_two_layers_70_nodi