#!/bin/bash
uv run python -m competitors.mmd_fair.simulation.main \
  --num_clients 20 \
  --num_rounds 50 \
  --dataset_name dutch \
  --dataset_path ../../../puffle/examples/data/dutch_csv/dutch.csv \
  --fed_dir ./training_data \
  --target_attribute occupation \
  --sensitive_attribute sex \
  --partitioner_type iid \
  --lambda_fairness 1.0 \
  --mu 1.0 \
  --ny 100 \
  --lr 0.01 \
  --momentum 0.9 \
  --weight_decay 0.00001 \
  --batch_size 32 \
  --num_epochs 1 \
  --seed 42 \
  --wandb True \
  --project_name MMD_Fair_Validation \
  --run_name test \
  --num_test_nodes 6 \
  --num_validation_nodes 4 \
  --num_train_nodes 10 \
  --sampled_validation_nodes_per_round 1.0 \
  --sampled_train_nodes_per_round 0 \
  --sampled_test_nodes_per_round 1.0